# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mvvmsample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mvvmsample
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'

  target 'mvvmsampleTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxTest',     '~> 4.0'
    pod 'RxBlocking',     '~> 4.0'
  end

  target 'mvvmsampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
